### ISSUE TITLE
Close old/stale PRs 

### ISSUE THREAD

**Issue by blallen** [CliMA/ClimateMachine.jl#1377]
# Description

We have a bunch of PRs that are many months old and can probably be closed. Going to mark them all here with likely suspects for triaging them. Arbitrarily choosing May 1st, 2020 as my cut-off for what's old. Please take a look and at least leave a comment on the PR updating where it stands. Thanks!

- [ ] #511 - @simonbyrne 
- [ ] #549 - @charleskawczynski 
- [ ] #556 - @charleskawczynski 
- [ ] #587 - @simonbyrne @lcw 
- [ ] #590 - @simonbyrne @charleskawczynski 
- [ ] #601 - @charleskawczynski @trontrytel 
- [ ] #606 - @simonbyrne @charleskawczynski @gagnelandmanna 
- [ ] #662 - @simonbyrne @sandreza @thomasgibson 
- [ ] #723 - @blallen (will be superceded in the next few days, will close once I port everything to a new PR)
- [ ] #807 - @akshaysridhar @charleskawczynski
- [ ] #859 - @slifer50 @akshaysridhar 
- [ ] #884 - @mwarusz @vchuravy 
- [ ] #966 - @charleskawczynski 
- [ ] #993 - @charleskawczynski @blallen 
- [ ] #1017 - @charleskawczynski 

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by charleskawczynski** [comment]
I just revived #1017 and, now with tooling that was added over time (specifically `error_on_non_convergence()`), it was a lot easier to test and ensure that the PR is an improvement over what we had 🚀. We should be able to merge #1017 today 😄

**Comment by blallen** [comment]
bump bump bump

been a month and only @charleskawczynski has tried to address this

**Comment by charleskawczynski** [comment]
I'm only a reviewer on a couple of these (590, 807). Others are low priority (993, 966), and @trontrytel is really the driver behind 601.

**Comment by trontrytel** [comment]
If 601 is a problem I can close it and reopen later.

**Comment by blallen** [comment]
> If 601 is a problem I can close it and reopen later.

It's not a problem, I just want to make sure the open PRs are things we actually intend to finish. Also sometimes when things get really stale, it's easier to start over with fresh PR on top of the current master.

**Comment by trontrytel** [comment]
> > If 601 is a problem I can close it and reopen later.
> 
> It's not a problem, I just want to make sure the open PRs are things we actually intend to finish. Also sometimes when things get really stale, it's easier to start over with fresh PR on top of the current master.

Done! You are prolly right. It will be easier to start fresh than to try to revive that one.

**Comment by bischtob** [comment]
@simonbyrne? @charleskawczynski? @blallen, when is this done? ABC = always be closing :-)!

**Comment by trontrytel** [comment]
Should I create an issue about old/stale issues and mention this one? ;)

**Comment by blallen** [comment]
> Should I create an issue about old/stale issues and mention this one? ;)

You see, I was waiting for this one to be finished before doing that (:
